# Generated by Django 4.2.3 on 2023-08-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-date_add",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="unique_constraint_ingredient_name_unit",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time_cook",
            field=models.PositiveSmallIntegerField(verbose_name="Время готовки"),
        ),
    ]
